# Specifies the version of the Docker Compose file format.
version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      # This line mounts your local private key into the container
      # The path on the left must be the ACTUAL path to YOUR key.
      - ~/.ssh/gcp_key:/root/.ssh/id_rsa:ro # Mounts as read-only for security
      # This volume is for hot-reloading
      - ./backend/src:/app/src
    command: npm run dev

  # Defines the frontend service.
  frontend:
    build:
      # The build context is the 'frontend' directory.
      context: ./frontend
      # We will create this Dockerfile in the next step.
      dockerfile: Dockerfile.frontend
    ports:
      # Maps port 3000 on your local machine to port 3000 in the container (for React).
      - "3000:3000"
    volumes:
      # Mounts the frontend's source code for hot-reloading.
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    # Ensures that the backend service is started before the frontend service.
    depends_on:
      - backend